--- #YAML:1.0
name: CGI-Formalware
version: 1.12
author:
  - Ron Savage <ron@savage.net.au>
abstract: Convert an XML file into a suite of CGI forms.
license: artistic
requires:
  CGI: 2.45
  Net::Telnet: 3.01
  XML::DOM: 1.14
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
